services:
  - type: web
    name: verify-udochain
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080

      # Mongo dual
      - key: MONGO_URI_VALIDATE
        sync: false
      - key: MONGO_URI_VERIFY
        sync: false

      # Aereware
      - key: AEREWARE_KEYFILE_JSON
        sync: false
      - key: AEREWARE_GATEWAY_HOST
        value: arweave.net
      - key: AEREWARE_GATEWAY_PORT
        value: "443"
      - key: AEREWARE_GATEWAY_PROTOCOL
        value: https

    staticPublishPath: public
